### PR TITLE
httpclient: allow to choose specific DNS server, print HTTP body

### PR DESCRIPTION
**Pull request by bassosimone**
Functionality that we're using with @xhdix

### CODE REVIEW

**Comment by bassosimone** [comment]
Please, @xhdix, take a look!

**Comment by xhdix** [comment]
@bassosimone Thanks.
I tested with two different DNS and it worked fine. The code is also looks good. (it would be better if we could also choose a specific DNS server for DoH or for all.)

**Comment by bassosimone** [comment]
> it would be better if we could also choose a specific DNS server for DoH or for all.)

Yeah, I guess this is a nice to have future improvement. I'm a bit swamped, so, if you want to submit a similar diff that adds this functionality, that would be awesome!

**Comment by xhdix** [comment]
Sure!

**Pull request merged**
